
services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:192.168.1.38"
  redis:
    image: 6.2-alpine
    ports:
      - "6379:6379"