
services:
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - REDIS_PASSWORD=Q7ZmVcBlZSJSWVJ0Yedu7K46dHf6MAnO
  app:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:192.168.1.38"
