
services:
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - REDIS_PASSWORD=Q7ZmVcBlZSJSWVJ0Yedu7K46dHf6MAnO
    networks:
      - connected_brain_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    container_name: connected_brain_web
    build:
        context: .
        dockerfile: ./apps/web/Dockerfile
    env_file: ./apps/web/.env
    ports:
      - "3000:3000"
#    extra_hosts:
#      - "host.docker.internal:192.168.1.38"
    networks:
      - connected_brain_network
  server:
    container_name: connected_brain_server
    build:
        context: .
        dockerfile: ./apps/server/Dockerfile
    env_file: ./apps/server/.env
    environment:
      - NODE_ENV=production
      - PORT=3001
      - REDIS_HOST=redis
    ports:
      - "3001:3001"
#    extra_hosts:
#      - "host.docker.internal:192.168.1.38"
    networks:
      - connected_brain_network
    depends_on:
      redis:
        condition: service_healthy
networks:
  connected_brain_network:
    driver: bridge
#    external: true # Use an existing network named app_network